// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
const shopifyStoreDomain =
  process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_DOMAIN ||
  process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN;
const shopifyAccessToken =
  process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN;

// --- TYPES ---
export interface ShopifyImage {
  url: string;
  altText: string;
}

export interface ShopifyMoney {
  amount: string;
  currencyCode: string;
}

export interface ShopifyProductVariant {
  id: string;
  title: string;
  price: ShopifyMoney;
  product?: {
    title: string;
    featuredImage: ShopifyImage;
  };
}

export interface ShopifyProduct {
  id: string;
  title: string;
  handle: string;
  description: string;
  productType: string;
  featuredImage: ShopifyImage;
  priceRange: {
    minVariantPrice: ShopifyMoney;
  };
  images: {
    edges: { node: ShopifyImage }[];
  };
  variants: {
    edges: { node: ShopifyProductVariant }[];
  };
}

export interface ShopifyProdocutEdge {
  node: ShopifyProduct;
}

export interface CartLineItem {
  id: string;
  quantity: number;
  attributes: { key: string; value: string }[];
  merchandise: ShopifyProductVariant;
}

export interface ShopifyCart {
  id: string;
  checkoutUrl: string;
  totalQuantity: number;
  lines: {
    edges: { node: CartLineItem }[];
  };
}

export interface ShopifyResponse<T> {
  data: T;
  errors?: any[];
}

async function ShopifyData<T>(
  query: string,
  variables?: Record<string, unknown>
): Promise<ShopifyResponse<T>> {
  const endpoint = `https://${shopifyStoreDomain}/api/2023-10/graphql.json`;

  const requestOptions = {
    method: "POST",
    headers: {
      "X-Shopify-Storefront-Access-Token": shopifyAccessToken!,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
    next: { revalidate: 3600 },
  };

  try {
    const response = await fetch(endpoint, requestOptions);
    const data = await response.json();

    if (data.errors) {
      console.error(
        "❌ Shopify API Errors:",
        JSON.stringify(data.errors, null, 2)
      );
    }

    return data as ShopifyResponse<T>;
  } catch (error) {
    console.error("❌ Shopify Fetch Error:", error);
    throw new Error("Failed to fetch products from Shopify");
  }
}

/** Autogenerated documentation for getAllProducts by Lukas Swarm. */
export async function getAllProducts(): Promise<ShopifyProdocutEdge[]> {
  const query = `
  {
    products(first: 250) {
      edges {
        node {
          id
          title
          handle
          description
          productType
          featuredImage {
            url
            altText
          }
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          images(first: 1) {
            edges {
              node {
                url
                altText
              }
            }
          }
          variants(first: 25) {
            edges {
              node {
                id
                title
                price {
                  amount
                  currencyCode
                }
              }
            }
          }
        }
      }
    }
  }`;

  const response = await ShopifyData<{
    products: { edges: ShopifyProdocutEdge[] };
  }>(query);
  return response.data.products.edges;
}

/** Autogenerated documentation for createCart by Lukas Swarm. */
export async function createCart(): Promise<ShopifyCart> {
  const query = `
    mutation cartCreate {
      cartCreate {
        cart {
          id
          checkoutUrl
        }
      }
    }
  `;
  const response = await ShopifyData<{ cartCreate: { cart: ShopifyCart } }>(
    query
  );
  return response.data.cartCreate.cart;
}

/** Autogenerated documentation for addToCart by Lukas Swarm. */
export async function addToCart(
  cartId: string,
  lines: {
    merchandiseId: string;
    quantity: number;
    attributes?: { key: string; value: string }[];
  }[]
): Promise<ShopifyCart> {
  const query = `
    mutation cartLinesAdd($cartId: ID!, $lines: [CartLineInput!]!) {
      cartLinesAdd(cartId: $cartId, lines: $lines) {
        cart {
          id
          checkoutUrl
          lines(first: 100) {
            edges {
              node {
                id
                quantity
                attributes {
                    key
                    value
                }
                merchandise {
                  ... on ProductVariant {
                    id
                    title
                    product {
                      title
                      featuredImage {
                        url
                        altText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData<{ cartLinesAdd: { cart: ShopifyCart } }>(
    query,
    { cartId, lines }
  );
  return response.data.cartLinesAdd.cart;
}

/** Autogenerated documentation for getCart by Lukas Swarm. */
export async function getCart(cartId: string): Promise<ShopifyCart> {
  const query = `
    query getCart($cartId: ID!) {
      cart(id: $cartId) {
        id
        checkoutUrl
        totalQuantity
        lines(first: 100) {
          edges {
            node {
              id
              quantity
              merchandise {
                ... on ProductVariant {
                  id
                  title
                  price {
                    amount
                    currencyCode
                  }
                  product {
                    title
                    featuredImage {
                      url
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData<{ cart: ShopifyCart }>(query, { cartId });
  return response.data.cart;
}

/** Autogenerated documentation for removeFromCart by Lukas Swarm. */
export async function removeFromCart(
  cartId: string,
  lineIds: string[]
): Promise<ShopifyCart> {
  const query = `
    mutation cartLinesRemove($cartId: ID!, $lineIds: [ID!]!) {
      cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
        cart {
          id
          checkoutUrl
          totalQuantity
          lines(first: 100) {
            edges {
              node {
                id
                quantity
                merchandise {
                  ... on ProductVariant {
                    id
                    title
                    price {
                      amount
                    }
                    product {
                      title
                      featuredImage {
                        url
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData<{
    cartLinesRemove: { cart: ShopifyCart };
  }>(query, { cartId, lineIds });
  return response.data.cartLinesRemove.cart;
}

/** Update cart line item quantity */
export async function updateCartLineQuantity(
  cartId: string,
  lineId: string,
  quantity: number
): Promise<ShopifyCart> {
  const query = `
    mutation cartLinesUpdate($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
      cartLinesUpdate(cartId: $cartId, lines: $lines) {
        cart {
          id
          checkoutUrl
          totalQuantity
          lines(first: 100) {
            edges {
              node {
                id
                quantity
                attributes {
                  key
                  value
                }
                merchandise {
                  ... on ProductVariant {
                    id
                    title
                    price {
                      amount
                      currencyCode
                    }
                    product {
                      title
                      featuredImage {
                        url
                        altText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData<{
    cartLinesUpdate: { cart: ShopifyCart };
  }>(query, {
    cartId,
    lines: [{ id: lineId, quantity }],
  });
  return response.data.cartLinesUpdate.cart;
}
