import { logRune, KINETIC_RUNES } from "./camelot";
import {
  ShopifyCart,
  ShopifyImage,
  ShopifyMoney,
  ShopifyProduct,
  ShopifyProductVariant,
  ShopifyProductEdge,
  ShopifyResponse,
  UserError,
  CartOperationResult,
} from "./shopify/types";
import { mockProducts } from "@/lib/shopify/mocks";

export type {
  ShopifyCart,
  ShopifyImage,
  ShopifyMoney,
  ShopifyProduct,
  ShopifyProductVariant,
  ShopifyProductEdge,
  ShopifyResponse,
  UserError,
  CartOperationResult,
};

const shopifyStoreDomain =
  process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_DOMAIN ||
  process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN;
const shopifyAccessToken =
  process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN;

if (!shopifyStoreDomain || !shopifyAccessToken) {
  logRune(KINETIC_RUNES.BYPASS, "Sovereign Mock Mode Activated (No credentials)");
} else {
  logRune(KINETIC_RUNES.ACTUATE, `Connecting to: ${shopifyStoreDomain}`);
}


async function ShopifyData<T>(
  query: string,
  variables?: Record<string, unknown>
): Promise<ShopifyResponse<T>> {
  if (!shopifyStoreDomain || !shopifyAccessToken) {
    console.warn("⚠️ Shopify credentials missing. Check your environment variables.");
    return {
      data: {} as T,
      errors: [{ message: "Shopify credentials missing" }]
    };
  }

  const endpoint = `https://${shopifyStoreDomain}/api/2023-10/graphql.json`;

  const requestOptions = {
    method: "POST",
    headers: {
      "X-Shopify-Storefront-Access-Token": shopifyAccessToken,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
    next: { revalidate: 3600 },
  };

  try {
    const response = await fetch(endpoint, requestOptions);
    if (!response.ok) {
      const errorText = await response.text();
      console.error(`❌ Shopify Fetch Error (HTTP ${response.status}):`, errorText);
      return { data: {} as T, errors: [{ message: `HTTP Error ${response.status}` }] };
    }
    const data = await response.json();

    if (data.errors) {
      console.error(
        "❌ Shopify API Errors:",
        JSON.stringify(data.errors, null, 2)
      );
    }

    return data as ShopifyResponse<T>;
  } catch (error) {
    console.error("❌ Shopify Fetch Network Error:", error);
    // Return empty data instead of throwing to prevent crashing the app
    return { data: {} as T, errors: [{ message: "Network error fetching from Shopify" }] };
  }
}

/** Autogenerated documentation for getAllProducts by Lukas Swarm. */
export async function getAllProducts(): Promise<ShopifyProductEdge[]> {
  const query = `
    query getProducts {
      products(first: 250) {
        edges {
          node {
            id
            title
            handle
            description
            productType
            featuredImage {
              url
              altText
            }
            priceRange {
              minVariantPrice {
                amount
                currencyCode
              }
            }
            images(first: 10) {
              edges {
                node {
                  url
                  altText
                }
              }
            }
            variants(first: 25) {
              edges {
                node {
                  id
                  title
                  availableForSale
                  quantityAvailable
                  price {
                    amount
                    currencyCode
                  }
                }
              }
            }
          }
        }
      }
    }
  `;

  let shopifyProducts: ShopifyProductEdge[] = [];
  try {
    const response = await ShopifyData<{
      products: { edges: ShopifyProductEdge[] };
    }>(query);

    if (response?.data?.products?.edges) {
      shopifyProducts = response.data.products.edges;
      logRune(KINETIC_RUNES.ACTUATE, `Fetched ${shopifyProducts.length} live products from Shopify.`);
    }
  } catch (error) {
    logRune(KINETIC_RUNES.BYPASS, "Shopify live fetch failed, using internal vault.");
  }



  // Logic: If live store is populated, use it. If no earrings in live, inject them from mock for now to keep feature visible.
  const hasLiveEarrings = shopifyProducts.some(p => p.node.productType.toLowerCase() === 'earrings');
  const finalizedProducts = [...shopifyProducts];

  if (!hasLiveEarrings) {
    const mockEarrings = mockProducts.filter(p => p.node.productType.toLowerCase() === 'earrings');
    finalizedProducts.push(...mockEarrings);
  }

  // If live store is very small or empty, add other mocks to fill the gallery
  if (shopifyProducts.length < 4) {
    const otherMocks = mockProducts.filter(p =>
      p.node.productType.toLowerCase() !== 'earrings' &&
      !shopifyProducts.some(lp => lp.node.handle === p.node.handle)
    );
    finalizedProducts.push(...otherMocks);
  }

  return finalizedProducts;
}



/** Autogenerated documentation for createCart by Lukas Swarm. */
export async function createCart(): Promise<ShopifyCart> {
  const query = `
    mutation cartCreate {
      cartCreate {
        cart {
        id
        checkoutUrl
      }
    }
  }
  `;
  const response = await ShopifyData<{ cartCreate: { cart: ShopifyCart } }>(
    query
  );

  if (!response?.data?.cartCreate?.cart) {
    console.warn("⚠️ Failed to create cart, using mock checkout session.");
    return {
      id: "mock-cart-id",
      checkoutUrl: "/checkout-fallback",
      totalQuantity: 0,
      lines: { edges: [] }
    };
  }

  return response.data.cartCreate.cart;
}


/** Autogenerated documentation for addToCart by Lukas Swarm. */
export async function addToCart(
  cartId: string,
  lines: {
    merchandiseId: string;
    quantity: number;
    attributes?: { key: string; value: string }[];
  }[]
): Promise<CartOperationResult> {
  const query = `
    mutation cartLinesAdd($cartId: ID!, $lines: [CartLineInput!]!) {
    cartLinesAdd(cartId: $cartId, lines: $lines) {
        cart {
        id
        checkoutUrl
        lines(first: 100) {
            edges {
              node {
              id
              quantity
                attributes {
                key
                value
              }
                merchandise {
                  ... on ProductVariant {
                  id
                  title
                    product {
                    title
                      featuredImage {
                      url
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
        userErrors {
        field
        message
      }
    }
  }
  `;
  const response = await ShopifyData<{ cartLinesAdd: { cart: ShopifyCart; userErrors: UserError[] } }>(
    query,
    { cartId, lines }
  );

  if (!response?.data?.cartLinesAdd) {
    return {
      cart: { id: cartId, checkoutUrl: "/checkout-fallback", totalQuantity: 0, lines: { edges: [] } },
      userErrors: [{ field: [], message: "Failed to add items to cart (API Unavailable)" }]
    };
  }

  return response.data.cartLinesAdd;
}

/** Autogenerated documentation for getCart by Lukas Swarm. */
export async function getCart(cartId: string): Promise<ShopifyCart> {
  const query = `
    query getCart($cartId: ID!) {
    cart(id: $cartId) {
      id
      checkoutUrl
      totalQuantity
      lines(first: 100) {
          edges {
            node {
            id
            quantity
              merchandise {
                ... on ProductVariant {
                id
                title
                  price {
                  amount
                  currencyCode
                }
                  product {
                  title
                    featuredImage {
                    url
                    altText
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  `;
  const response = await ShopifyData<{ cart: ShopifyCart }>(query, { cartId });

  if (!response?.data?.cart) {
    return {
      id: cartId,
      checkoutUrl: "/checkout-fallback",
      totalQuantity: 0,
      lines: { edges: [] }
    };
  }

  return response.data.cart;
}

/** Autogenerated documentation for removeFromCart by Lukas Swarm. */
export async function removeFromCart(
  cartId: string,
  lineIds: string[]
): Promise<ShopifyCart> {
  const query = `
    mutation cartLinesRemove($cartId: ID!, $lineIds: [ID!]!) {
    cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
        cart {
        id
        checkoutUrl
        totalQuantity
        lines(first: 100) {
            edges {
              node {
              id
              quantity
                merchandise {
                  ... on ProductVariant {
                  id
                  title
                    price {
                    amount
                  }
                    product {
                    title
                      featuredImage {
                      url
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  `;
  const response = await ShopifyData<{
    cartLinesRemove: { cart: ShopifyCart };
  }>(query, { cartId, lineIds });

  if (!response?.data?.cartLinesRemove?.cart) {
    return {
      id: cartId,
      checkoutUrl: "/checkout-fallback",
      totalQuantity: 0,
      lines: { edges: [] }
    };
  }

  return response.data.cartLinesRemove.cart;
}

/** Update cart line item quantity */
export async function updateCartLineQuantity(
  cartId: string,
  lineId: string,
  quantity: number
): Promise<CartOperationResult> {
  const query = `
    mutation cartLinesUpdate($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
    cartLinesUpdate(cartId: $cartId, lines: $lines) {
        cart {
        id
        checkoutUrl
        totalQuantity
        lines(first: 100) {
            edges {
              node {
              id
              quantity
                attributes {
                key
                value
              }
                merchandise {
                  ... on ProductVariant {
                  id
                  title
                    price {
                    amount
                    currencyCode
                  }
                    product {
                    title
                      featuredImage {
                      url
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
        userErrors {
        field
        message
      }
    }
  }
  `;
  const response = await ShopifyData<{
    cartLinesUpdate: { cart: ShopifyCart; userErrors: UserError[] };
  }>(query, {
    cartId,
    lines: [{ id: lineId, quantity }],
  });

  if (!response?.data?.cartLinesUpdate) {
    return {
      cart: { id: cartId, checkoutUrl: "/checkout-fallback", totalQuantity: 0, lines: { edges: [] } },
      userErrors: [{ field: [], message: "Failed to update quantity (API Unavailable)" }]
    };
  }

  return response.data.cartLinesUpdate;
}
