// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
const shopifyStoreDomain = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN;
const shopifyAccessToken = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN;

async function ShopifyData(query: string, variables?: Record<string, any>) {
  const endpoint = `https://${shopifyStoreDomain}/api/2023-10/graphql.json`;

  const requestOptions = {
    method: "POST",
    headers: {
      "X-Shopify-Storefront-Access-Token": shopifyAccessToken!,
      "Accept": "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
    next: { revalidate: 0 },
  };

  try {
    const response = await fetch(endpoint, requestOptions);
    const data = await response.json();
    
    if (data.errors) {
      console.error('❌ Shopify API Errors:', JSON.stringify(data.errors, null, 2));
    }
    
    return data;
  } catch (error) {
    console.error('❌ Shopify Fetch Error:', error);
    throw new Error("Failed to fetch products from Shopify");
  }
}

/** Autogenerated documentation for getAllProducts by Lukas Swarm. */
export async function getAllProducts() {
  const query = `
  {
    products(first: 20) {
      edges {
        node {
          id
          title
          handle
          description
          productType
          featuredImage {
            url
            altText
          }
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          images(first: 1) {
            edges {
              node {
                url
                altText
              }
            }
          }
          variants(first: 1) {
            edges {
              node {
                id
                title
                price {
                  amount
                  currencyCode
                }
              }
            }
          }
        }
      }
    }
  }`;

  const response = await ShopifyData(query);
  return response.data.products.edges;
}

/** Autogenerated documentation for createCart by Lukas Swarm. */
export async function createCart() {
  const query = `
    mutation cartCreate {
      cartCreate {
        cart {
          id
          checkoutUrl
        }
      }
    }
  `;
  const response = await ShopifyData(query);
  return response.data.cartCreate.cart;
}

/** Autogenerated documentation for addToCart by Lukas Swarm. */
export async function addToCart(cartId: string, lines: { merchandiseId: string; quantity: number }[]) {
  const query = `
    mutation cartLinesAdd($cartId: ID!, $lines: [CartLineInput!]!) {
      cartLinesAdd(cartId: $cartId, lines: $lines) {
        cart {
          id
          checkoutUrl
          lines(first: 100) {
            edges {
              node {
                id
                quantity
                merchandise {
                  ... on ProductVariant {
                    id
                    title
                    product {
                      title
                      featuredImage {
                        url
                        altText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData(query, { cartId, lines });
  return response.data.cartLinesAdd.cart;
}

/** Autogenerated documentation for getCart by Lukas Swarm. */
export async function getCart(cartId: string) {
  const query = `
    query getCart($cartId: ID!) {
      cart(id: $cartId) {
        id
        checkoutUrl
        totalQuantity
        lines(first: 100) {
          edges {
            node {
              id
              quantity
              merchandise {
                ... on ProductVariant {
                  id
                  title
                  price {
                    amount
                    currencyCode
                  }
                  product {
                    title
                    featuredImage {
                      url
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  `;
  const response = await ShopifyData(query, { cartId });
  return response.data.cart;
}
