// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/** Autogenerated documentation for cn by Lukas Swarm. */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/** Autogenerated documentation for formatCurrency by Lukas Swarm. */
export function formatCurrency(amount: number) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);
}
