// 🐝 [HIVE_SWARM_STAMP] Autonomously Extracted by Anya Sharma & Synced with Shopify
// Generated by scripts/sync_shopify_all.js at 2026-02-27T01:24:45.971Z
import { ShopifyProductEdge } from "./types";

export const mockProducts: ShopifyProductEdge[] = [
    {
        "node": {
            "id": "gid://shopify/Product/14929748459890",
            "title": "Personal Care - 1000011817",
            "handle": "handmade-keychain-1000011817",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000011817.jpg?v=1767069006",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000011817.jpg?v=1767069006",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475653943666",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748492658",
            "title": "Personal Care - 1000012019",
            "handle": "handmade-keychain-1000012019",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020990.jpg?v=1767101661",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020990.jpg?v=1767101661",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475653976434",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748525426",
            "title": "Personal Care - 1000012138",
            "handle": "handmade-keychain-1000012138",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_26e97800-b43b-45c0-813c-8409f6a5c3ea.jpg?v=1767160415",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_26e97800-b43b-45c0-813c-8409f6a5c3ea.jpg?v=1767160415",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654009202",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748558194",
            "title": "Personal Care - 1000012195",
            "handle": "handmade-keychain-1000012195",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012195.jpg?v=1767069019",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012195.jpg?v=1767069019",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654041970",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748590962",
            "title": "Personal Care - 1000012197",
            "handle": "handmade-keychain-1000012197",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012197.jpg?v=1767069023",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012197.jpg?v=1767069023",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654074738",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748623730",
            "title": "Personal Care - 1473986136160",
            "handle": "handmade-keychain-1473986136160",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_ff0c7eb9-ef4e-44a4-b519-4391292db40c.jpg?v=1767160684",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_ff0c7eb9-ef4e-44a4-b519-4391292db40c.jpg?v=1767160684",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654107506",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748656498",
            "title": "Personal Care - 1474164466462",
            "handle": "handmade-keychain-1474164466462",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_91b131a4-9187-426f-8b36-8bfbf3a1d00e.jpg?v=1767160793",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_91b131a4-9187-426f-8b36-8bfbf3a1d00e.jpg?v=1767160793",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654140274",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748722034",
            "title": "Epic Custom - 1529285017581-529",
            "handle": "handmade-keychain-1529285017581-529",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529.jpg?v=1767069028",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529.jpg?v=1767069028",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654205810",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748754802",
            "title": "Purely Basic - 20180228_134138",
            "handle": "handmade-keychain-20180228_134138",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180228_134138.jpg?v=1767069031",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "2.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180228_134138.jpg?v=1767069031",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654238578",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "2.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748787570",
            "title": "Purely Basic - 20180228_134358",
            "handle": "handmade-keychain-20180228_134358",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180228_134358.jpg?v=1767069033",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "2.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180228_134358.jpg?v=1767069033",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654271346",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "2.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748820338",
            "title": "Personal Care - 20180419_165849",
            "handle": "handmade-keychain-20180419_165849",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_769ec8f9-9d74-41ef-9536-73598a2e81ca.jpg?v=1767161105",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_769ec8f9-9d74-41ef-9536-73598a2e81ca.jpg?v=1767161105",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654304114",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748853106",
            "title": "Purely Basic - 20180605_225108",
            "handle": "handmade-keychain-20180605_225108",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_1b142321-ac69-499e-a451-4c6b5b7d6c1d.jpg?v=1767106019",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "2.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_1b142321-ac69-499e-a451-4c6b5b7d6c1d.jpg?v=1767106019",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654336882",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "2.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748885874",
            "title": "Epic Custom - 20180605_225132",
            "handle": "handmade-keychain-20180605_225132",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_35f07557-2230-4e49-a9f6-cd931016029e.jpg?v=1767105911",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_35f07557-2230-4e49-a9f6-cd931016029e.jpg?v=1767105911",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654369650",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748918642",
            "title": "Epic Custom - 20180707_193545",
            "handle": "handmade-keychain-20180707_193545",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529_6afaef96-c28b-4225-9aa9-4f1d91f22773.jpg?v=1767101675",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529_6afaef96-c28b-4225-9aa9-4f1d91f22773.jpg?v=1767101675",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654435186",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929748951410",
            "title": "Personal Care - 20180711_211046",
            "handle": "handmade-keychain-20180711_211046",
            "description": "Handcrafted with love. This unique keychain features a custom weave and premium materials.",
            "productType": "Woven",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180711_211046.jpg?v=1767069046",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/20180711_211046.jpg?v=1767069046",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_d3fdf1ec-8820-4b96-ac7c-21860d8bdf49.jpg?v=1770053348",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475654467954",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929841815922",
            "title": "Personal Care - 1000011817",
            "handle": "handmade-keychain-1000011818",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000011817_82fe5d0e-e2ba-4de7-89f1-211bf53bc43e.jpg?v=1767101641",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000011817_82fe5d0e-e2ba-4de7-89f1-211bf53bc43e.jpg?v=1767101641",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986440562",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929841848690",
            "title": "Personal Care - 1000012019",
            "handle": "handmade-keychain-1000012020",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_bdbd91de-0eda-4ac4-99a5-9e6bbf0aa0f9.jpg?v=1767105650",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_bdbd91de-0eda-4ac4-99a5-9e6bbf0aa0f9.jpg?v=1767105650",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986473330",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929841881458",
            "title": "Personal Care - 1000012138",
            "handle": "handmade-keychain-1000012139",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5ada6437-3b5d-4ec2-b187-4e88b19614ca.jpg?v=1767160949",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5ada6437-3b5d-4ec2-b187-4e88b19614ca.jpg?v=1767160949",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986506098",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929841914226",
            "title": "Personal Care - 1000012195",
            "handle": "handmade-keychain-1000012196",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012195_07d4218f-5f90-456b-8ec0-3adc8021d1cc.jpg?v=1767101654",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012195_07d4218f-5f90-456b-8ec0-3adc8021d1cc.jpg?v=1767101654",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986571634",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929841979762",
            "title": "Personal Care - 1000012197",
            "handle": "handmade-keychain-1000012198",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012197_64ecdd8f-522a-4421-a7d1-3819b4598e45.jpg?v=1767101658",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000012197_64ecdd8f-522a-4421-a7d1-3819b4598e45.jpg?v=1767101658",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986637170",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842012530",
            "title": "Personal Care - 1000020990",
            "handle": "handmade-keychain-1000020990",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020990.jpg?v=1767101661",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020990.jpg?v=1767101661",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986669938",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842045298",
            "title": "Personal Care - 1000020991",
            "handle": "handmade-keychain-1000020991",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020991.jpg?v=1767101664",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020991.jpg?v=1767101664",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986702706",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842078066",
            "title": "Epic Custom - 1000020992",
            "handle": "handmade-keychain-1000020992",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020992.jpg?v=1767101667",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020992.jpg?v=1767101667",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986735474",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842110834",
            "title": "Personal Care - 1000020993",
            "handle": "handmade-keychain-1000020993",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020993.jpg?v=1767101669",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1000020993.jpg?v=1767101669",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986768242",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842143602",
            "title": "Personal Care - 1473986136160",
            "handle": "handmade-keychain-1473986136161",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_2aeae509-0c6d-4d98-b33d-e858f259af31.jpg?v=1767105459",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_2aeae509-0c6d-4d98-b33d-e858f259af31.jpg?v=1767105459",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986801010",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842176370",
            "title": "Personal Care - 1474164466462",
            "handle": "handmade-keychain-1474164466463",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_bdbd91de-0eda-4ac4-99a5-9e6bbf0aa0f9.jpg?v=1767105650",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_bdbd91de-0eda-4ac4-99a5-9e6bbf0aa0f9.jpg?v=1767105650",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986833778",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842209138",
            "title": "Epic Custom - 1529285017581-529",
            "handle": "handmade-keychain-1529285017581-530",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529_6afaef96-c28b-4225-9aa9-4f1d91f22773.jpg?v=1767101675",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/1529285017581-529_6afaef96-c28b-4225-9aa9-4f1d91f22773.jpg?v=1767101675",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986866546",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842241906",
            "title": "Purely Basic - 20180228_134138",
            "handle": "handmade-keychain-20180228_134138-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a7232010-95bb-422a-bb41-cd574b7f0b79.jpg?v=1770742143",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "2.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a7232010-95bb-422a-bb41-cd574b7f0b79.jpg?v=1770742143",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986899314",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "2.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842274674",
            "title": "Purely Basic - 20180228_134358",
            "handle": "handmade-keychain-20180228_134358-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_f29209f6-c2b1-45e6-ac0a-b25ef3c678e2.jpg?v=1767160041",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "2.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_f29209f6-c2b1-45e6-ac0a-b25ef3c678e2.jpg?v=1767160041",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_db08bd35-8233-41f2-842b-d5ef86be90d2.jpg?v=1767160078",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986932082",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "2.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842307442",
            "title": "Epic Custom - 20180419_165849",
            "handle": "handmade-keychain-20180419_165849-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_c6bc722e-f4d1-40bc-bf4a-d2192d1ee8b9.jpg?v=1771420898",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "9.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_c6bc722e-f4d1-40bc-bf4a-d2192d1ee8b9.jpg?v=1771420898",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986964850",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "9.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842340210",
            "title": "Personal Care - 20180605_225108",
            "handle": "handmade-keychain-20180605_225108-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_85891980-fd87-4abd-a6dc-61cdb8e1371f.jpg?v=1767159682",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_85891980-fd87-4abd-a6dc-61cdb8e1371f.jpg?v=1767159682",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475986997618",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842372978",
            "title": "Personal Care - 20180605_225132",
            "handle": "handmade-keychain-20180605_225132-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_d3fdf1ec-8820-4b96-ac7c-21860d8bdf49.jpg?v=1770053348",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_d3fdf1ec-8820-4b96-ac7c-21860d8bdf49.jpg?v=1770053348",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475987030386",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842405746",
            "title": "Personal Care - 20180707_193545",
            "handle": "handmade-keychain-20180707_193545-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Keychain",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_2aeae509-0c6d-4d98-b33d-e858f259af31.jpg?v=1767105459",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "5.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_2aeae509-0c6d-4d98-b33d-e858f259af31.jpg?v=1767105459",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475987063154",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "5.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14929842438514",
            "title": "Dangle in style - price per pair 20180711_211046",
            "handle": "handmade-keychain-20180711_211046-1",
            "description": "Hand-woven with love.A unique piece from Lisa's collection.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5c31e416-3eb7-4e4f-839c-0542e153541e.jpg?v=1770333876",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "6.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5c31e416-3eb7-4e4f-839c-0542e153541e.jpg?v=1770333876",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61475987095922",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "6.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14976140837234",
            "title": "Dangle in style- price per set.",
            "handle": "handmade-heart-earrings-1",
            "description": "Authentic Lisa Custom Earrings. Handcrafted heart design.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_b15e551f-12e0-439e-acba-e488448f437e.jpg?v=1771451778",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "8.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_b15e551f-12e0-439e-acba-e488448f437e.jpg?v=1771451778",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_07f77453-a6c8-4d37-baa9-0515661b08e3.jpg?v=1771451778",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_15c15c93-08ad-4b26-8436-9d3674f03d15.jpg?v=1771861266",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5842479c-bc88-4a11-9291-963cca4ff366.jpg?v=1771861783",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61587685409138",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "8.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14976140870002",
            "title": "Dangle in style",
            "handle": "custom-charm-earrings-1",
            "description": "Authentic Lisa Custom Earrings. Personalize with your choice of charms.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_1_b00c6ab4-6b6e-4a68-9874-d274b8efe775.jpg?v=1770869040",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "6.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_1_b00c6ab4-6b6e-4a68-9874-d274b8efe775.jpg?v=1770869040",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61587685605746",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "6.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14976140902770",
            "title": "Dangle in style",
            "handle": "boho-weave-earrings-1",
            "description": "Authentic Lisa Custom Earrings. Intricate woven pattern.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a0f939a3-5217-4d85-82e8-c4a7e12abf6c.jpg?v=1770987253",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "6.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a0f939a3-5217-4d85-82e8-c4a7e12abf6c.jpg?v=1770987253",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61587685638514",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "6.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14977434255730",
            "title": "Matching Pair - Set",
            "handle": "handmade-heart-earrings-2",
            "description": "Authentic Lisa Custom Earrings and Keychain. Get it in a set.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_15c15c93-08ad-4b26-8436-9d3674f03d15.jpg?v=1771861266",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "8.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_15c15c93-08ad-4b26-8436-9d3674f03d15.jpg?v=1771861266",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_ed159705-1876-4bbc-8c1d-91916abf849a.jpg?v=1771861265",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_297e5aad-5b4d-4353-be67-bc05399ed526.jpg?v=1771861266",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_5842479c-bc88-4a11-9291-963cca4ff366.jpg?v=1771861783",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_6760a0ca-77cf-4c37-958a-0444eaee2d62.jpg?v=1771876596",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_9d15c051-1115-42aa-81ae-e8a98c37ca79.jpg?v=1771945945",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_92f9b396-909e-4fa3-8a0f-f8b1f852be61.jpg?v=1771945945",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_188b3890-e786-446d-b440-88c0529bc629.jpg?v=1771945945",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61589670789490",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "8.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14977434288498",
            "title": "Dangle in Style",
            "handle": "custom-charm-earrings-2",
            "description": "Authentic Lisa Custom Earrings. Personalize with your choice of charms.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a366ada6-fab2-48e6-b7de-91b7c8df442d.jpg?v=1770870122",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "6.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_a366ada6-fab2-48e6-b7de-91b7c8df442d.jpg?v=1770870122",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_9ae8d54e-59bc-4e51-a6fd-c4796664d714.jpg?v=1770870122",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_e74907e5-c55e-4d2e-8530-f0b36860bfc4.jpg?v=1770870122",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_63e072b7-9438-460a-ac50-00149fd04803.jpg?v=1770870122",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_33b1ca36-cfa8-43b2-bbce-7c322ee82cbe.jpg?v=1770870122",
                            "altText": null
                        }
                    },
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/rn-image_picker_lib_temp_98a03c30-f7ac-4484-9bf5-67001733d32c.jpg?v=1770870122",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61589670822258",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "6.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14977434321266",
            "title": "Dangle in style",
            "handle": "boho-weave-earrings-2",
            "description": "Authentic Lisa Custom Earrings. Intricate woven pattern.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_3_5826f8e9-90da-42c4-b3fe-0a81bd092fa7.jpg?v=1770891138",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "6.95",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_3_5826f8e9-90da-42c4-b3fe-0a81bd092fa7.jpg?v=1770891138",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61589670855026",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "6.95",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14987223466354",
            "title": "Handmade Heart Earrings",
            "handle": "handmade-heart-earrings-3",
            "description": "Authentic Lisa Custom Earrings. Handcrafted heart design.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_1_ddca58d6-e4a0-403c-abb9-e50bcb38084e.jpg?v=1772138984",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "15.0",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_1_ddca58d6-e4a0-403c-abb9-e50bcb38084e.jpg?v=1772138984",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61622984311154",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "15.0",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14987223564658",
            "title": "Custom Charm Earrings",
            "handle": "custom-charm-earrings-3",
            "description": "Authentic Lisa Custom Earrings. Personalize with your choice of charms.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_2_6d1afa3d-0cff-4e20-a410-08d9b3bf5b3d.jpg?v=1772138987",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "15.0",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_2_6d1afa3d-0cff-4e20-a410-08d9b3bf5b3d.jpg?v=1772138987",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61622984474994",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "15.0",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    },
    {
        "node": {
            "id": "gid://shopify/Product/14987223761266",
            "title": "Boho Weave Earrings",
            "handle": "boho-weave-earrings-3",
            "description": "Authentic Lisa Custom Earrings. Intricate woven pattern.",
            "productType": "Earrings",
            "featuredImage": {
                "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_3_e74016f5-932f-4758-a3d7-fcdf59a3bd87.jpg?v=1772138989",
                "altText": null
            },
            "priceRange": {
                "minVariantPrice": {
                    "amount": "15.0",
                    "currencyCode": "USD"
                }
            },
            "images": {
                "edges": [
                    {
                        "node": {
                            "url": "https://cdn.shopify.com/s/files/1/0952/7151/8578/files/earrings_3_e74016f5-932f-4758-a3d7-fcdf59a3bd87.jpg?v=1772138989",
                            "altText": null
                        }
                    }
                ]
            },
            "variants": {
                "edges": [
                    {
                        "node": {
                            "id": "gid://shopify/ProductVariant/61622984671602",
                            "title": "Default Title",
                            "availableForSale": true,
                            "price": {
                                "amount": "15.0",
                                "currencyCode": "USD"
                            }
                        }
                    }
                ]
            }
        }
    }
];
