"use client";

import { useEffect, useState, useCallback } from "react";
import { Sparkles, RefreshCw, CheckCheck, Loader2 } from "lucide-react";

type ContentItem = {
  id: string;
  type: string;
  title: string;
  body: string;
  status: "pending" | "approved" | "rejected";
  createdAt: string;
};

const STATUS_COLORS: Record<ContentItem["status"], string> = {
  pending:  "bg-amber-50 border-amber-200 text-amber-800",
  approved: "bg-emerald-50 border-emerald-200 text-emerald-800",
  rejected: "bg-red-50 border-red-200 text-red-700",
};

const STATUS_DOT: Record<ContentItem["status"], string> = {
  pending:  "bg-amber-400",
  approved: "bg-emerald-500",
  rejected: "bg-red-400",
};

export default function ContentCalendar() {
  const [items, setItems] = useState<ContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [editBody, setEditBody] = useState("");

  const fetchQueue = useCallback(() => {
    fetch("/api/content-queue")
      .then((r) => r.json())
      .then((data) => {
        setItems(Array.isArray(data) ? data : []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  useEffect(() => {
    fetchQueue();
    const handleUpdate = () => fetchQueue();
    window.addEventListener("content-queue-updated", handleUpdate);
    return () => window.removeEventListener("content-queue-updated", handleUpdate);
  }, [fetchQueue]);

  async function generateAiDrafts() {
    if (generating) return;
    setGenerating(true);
    try {
      const res = await fetch("/api/bob/draft-posts", { method: "POST" });
      if (res.ok) {
        const data = await res.json();
        const drafts = data.drafts || [];
        for (const draft of drafts) {
          await fetch("/api/content-queue", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              type: `social-${draft.platform}`,
              title: `${draft.platform.toUpperCase()} Artisan Post — ${draft.content.slice(0, 32)}...`,
              body: `${draft.content}\n\n${(draft.hashtags || []).join(" ")}`,
            }),
          });
        }
        fetchQueue();
      }
    } catch (e) {
      console.error("AI draft generation error:", e);
    } finally {
      setGenerating(false);
    }
  }

  async function approveAllPending() {
    const pendings = items.filter((i) => i.status === "pending");
    for (const item of pendings) {
      await updateItem(item.id, "approved");
    }
  }

  async function updateItem(id: string, status: ContentItem["status"], body?: string) {
    const res = await fetch("/api/content-queue", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, status, body }),
    });
    if (res.ok) {
      const updated: ContentItem = await res.json();
      setItems((prev) => prev.map((item) => (item.id === id ? updated : item)));
    }
    setEditing(null);
  }

  const pending  = items.filter((i) => i.status === "pending").length;
  const approved = items.filter((i) => i.status === "approved").length;
  const rejected = items.filter((i) => i.status === "rejected").length;

  return (
    <div className="bg-white border border-gray-200 p-6 shadow-sm">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4 border-b pb-3">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-purple-600" />
            <h2 className="text-xs uppercase tracking-[0.2em] font-bold text-gray-900">
              AI Content Queue & Review Stream
            </h2>
          </div>
          <p className="text-[11px] text-gray-400 mt-0.5">
            Artisan posts, campaigns, and headlines generated by Sir BoB & Gemini
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={generateAiDrafts}
            disabled={generating}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-700 hover:bg-purple-800 text-white rounded text-[10px] font-black uppercase tracking-wider transition-colors disabled:opacity-50"
          >
            {generating ? (
              <>
                <Loader2 className="w-3 h-3 animate-spin" />
                <span>Synthesizing...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3 h-3" />
                <span>Auto-Draft with AI</span>
              </>
            )}
          </button>

          {pending > 0 && (
            <button
              onClick={approveAllPending}
              className="flex items-center gap-1 px-2.5 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded text-[10px] font-bold uppercase tracking-wider transition-colors"
            >
              <CheckCheck className="w-3 h-3" />
              <span>Approve All</span>
            </button>
          )}

          <div className="flex gap-2 text-[10px] font-mono uppercase tracking-wider ml-2">
            <span className="text-amber-700 font-bold">{pending} pending</span>
            <span className="text-emerald-700 font-bold">{approved} approved</span>
          </div>
        </div>
      </div>

      {loading && (
        <p className="text-xs text-gray-400 animate-pulse">Loading queue…</p>
      )}

      {!loading && items.length === 0 && (
        <div className="text-center py-8 border-2 border-dashed border-gray-100 rounded-lg">
          <Sparkles className="w-8 h-8 text-purple-300 mx-auto mb-2" />
          <p className="text-xs font-semibold text-gray-700">AI Content Queue is Ready</p>
          <p className="text-[11px] text-gray-400 mt-1 max-w-sm mx-auto">
            Click &quot;Auto-Draft with AI&quot; above to synthesize a week of handcrafted Instagram, TikTok, and Facebook posts.
          </p>
          <button
            onClick={generateAiDrafts}
            disabled={generating}
            className="mt-4 px-4 py-2 bg-slate-900 hover:bg-purple-700 text-white text-[10px] font-black uppercase tracking-widest rounded-lg transition"
          >
            Generate This Week&apos;s Posts
          </button>
        </div>
      )}

      <ul className="space-y-4">
        {items.map((item) => (
          <li
            key={item.id}
            className={`rounded border p-4 ${STATUS_COLORS[item.status]}`}
          >
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2">
                <span className={`w-2 h-2 rounded-full flex-shrink-0 mt-0.5 ${STATUS_DOT[item.status]}`} />
                <div>
                  <span className="text-[10px] uppercase tracking-wider font-bold opacity-60">
                    {item.type}
                  </span>
                  <p className="text-sm font-bold leading-snug">{item.title}</p>
                </div>
              </div>
              <span className="text-[10px] opacity-50 whitespace-nowrap">
                {new Date(item.createdAt).toLocaleDateString()}
              </span>
            </div>

            {editing === item.id ? (
              <div className="mt-3 space-y-2">
                <textarea
                  value={editBody}
                  onChange={(e) => setEditBody(e.target.value)}
                  className="w-full rounded border border-gray-300 bg-white p-2 text-xs text-gray-800 outline-none focus:border-purple-400 focus:ring-2 focus:ring-purple-100 min-h-20"
                />
                <div className="flex gap-2">
                  <button
                    onClick={() => updateItem(item.id, "approved", editBody)}
                    className="px-3 py-1 text-[10px] uppercase tracking-widest font-bold bg-emerald-600 text-white rounded hover:bg-emerald-700"
                  >
                    Save & Approve
                  </button>
                  <button
                    onClick={() => setEditing(null)}
                    className="px-3 py-1 text-[10px] uppercase tracking-widest font-bold border border-gray-300 text-gray-600 rounded hover:bg-gray-50"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <>
                <p className="mt-2 text-xs leading-relaxed opacity-80">{item.body}</p>
                {item.status === "pending" && (
                  <div className="flex gap-2 mt-3">
                    <button
                      onClick={() => updateItem(item.id, "approved")}
                      className="px-3 py-1 text-[10px] uppercase tracking-widest font-bold bg-emerald-600 text-white rounded hover:bg-emerald-700"
                    >
                      Approve
                    </button>
                    <button
                      onClick={() => { setEditing(item.id); setEditBody(item.body); }}
                      className="px-3 py-1 text-[10px] uppercase tracking-widest font-bold border border-amber-400 text-amber-800 rounded hover:bg-amber-100"
                    >
                      Edit
                    </button>
                    <button
                      onClick={() => updateItem(item.id, "rejected")}
                      className="px-3 py-1 text-[10px] uppercase tracking-widest font-bold border border-red-300 text-red-700 rounded hover:bg-red-50"
                    >
                      Reject
                    </button>
                  </div>
                )}
                {item.status !== "pending" && (
                  <button
                    onClick={() => updateItem(item.id, "pending")}
                    className="mt-2 text-[10px] uppercase tracking-widest text-gray-400 hover:text-gray-700 transition-colors"
                  >
                    Reset to pending
                  </button>
                )}
              </>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}
