"use client";

import { useState } from "react";
import { ClipboardList, Loader2, X } from "lucide-react";

// Per-event pop-up prep list, generated by Sir BoB from the event details.
export default function PopupPrep({ title, date, location }: { title: string; date: string; location: string }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [list, setList] = useState("");

  const generate = async () => {
    setOpen(true);
    if (list) return;
    setLoading(true);
    try {
      const res = await fetch("/api/bob/owner-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [
            {
              role: "user",
              content: `Lisa has a pop-up vending event: "${title}" on ${date} at ${location}. Generate a practical prep checklist for a handmade keychain vendor: inventory to pack, display/signage, payment setup, lead capture (quote forms, QR codes), and day-of timeline. Keep it scannable — short bullet lines, no emojis, under 200 words.`,
            },
          ],
        }),
      });
      const data = await res.json();
      setList(data.reply || "BoB could not generate the list.");
    } catch {
      setList("Prep list failed — try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <button
        onClick={generate}
        className="mt-2 flex items-center gap-1 text-[10px] font-black uppercase tracking-widest text-purple-700 hover:text-purple-900"
      >
        <ClipboardList className="w-3 h-3" /> Prep list
      </button>
      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setOpen(false)}>
          <div
            className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-6 max-h-[80vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-black uppercase tracking-widest text-slate-900">
                Prep: {title}
              </h3>
              <button onClick={() => setOpen(false)} className="text-slate-400 hover:text-slate-600" aria-label="Close">
                <X className="w-4 h-4" />
              </button>
            </div>
            {loading ? (
              <div className="flex items-center gap-2 text-sm text-slate-500 py-6">
                <Loader2 className="w-4 h-4 animate-spin" /> BoB is packing the list…
              </div>
            ) : (
              <p className="text-sm text-slate-700 whitespace-pre-wrap leading-relaxed">{list}</p>
            )}
          </div>
        </div>
      )}
    </>
  );
}
