// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import type { Metadata } from "next";
import { Playfair_Display, Quicksand } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../components/CartProvider";
import { NotificationProvider } from "../components/NotificationSentry";
import StorefrontShell from "../components/StorefrontShell";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Lisa's Custom Keychains | Premium Macrame",
  description:
    "Design your custom macrame keychains live. Handcrafted quality, instant previews.",
  metadataBase: new URL("https://www.lisascustomkeychains.com"),
};

/** Autogenerated documentation for RootLayout by Lukas Swarm. */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${quicksand.variable} ${playfair.variable} font-sans antialiased text-slate-800 selection:bg-purple-200 selection:text-purple-900 overflow-x-hidden min-h-screen flex flex-col`}
      >
        <NotificationProvider>
          <CartProvider>
            {children}
            <StorefrontShell />
          </CartProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
