// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import Navbar from "../components/Navbar";
import ProductGrid from "../components/ProductGrid";
import { getAllProducts } from "../lib/shopify";
import {
  Sparkles,
  Heart,
  Instagram,
  Facebook,
  Mail,
  HeartHandshake,
} from "lucide-react";
import AboutSection from "../components/AboutSection";

export const dynamic = "force-dynamic";

/** Autogenerated documentation for Home by Lukas Swarm. */
export default async function Home() {
  let products: Awaited<ReturnType<typeof getAllProducts>> = [];
  try {
    products = await getAllProducts();
  } catch (e) {
    console.error("Shopify Fetch Error:", e);
  }

  return (
    <div className="min-h-screen text-slate-800">
      <Navbar />

      <div className="h-32"></div>

      <main className="max-w-7xl mx-auto px-6 pb-24 relative z-10">
        {/* HERO SECTION */}
        <div className="grid md:grid-cols-2 gap-12 items-center py-12 mb-20">
          <div className="text-center md:text-left space-y-6">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-100 rounded-full text-purple-900 text-xs font-bold tracking-wider uppercase">
              <Sparkles className="w-3 h-3" />
              <span>Handcrafted With Love</span>
            </div>

            <h2 className="text-5xl md:text-6xl font-serif italic leading-tight text-slate-900">
              Every Knot
              <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-600 via-pink-600 to-rose-600">
                Tells a Story
              </span>
            </h2>

            <p className="text-lg text-slate-600 leading-relaxed max-w-xl mx-auto md:mx-0">
              From my hands to yours. Each keychain is lovingly woven with
              heart. Not mass-produced. Just handmade magic.
            </p>

            <div className="flex flex-wrap gap-6 pt-4 justify-center md:justify-start">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
                  <HeartHandshake className="text-purple-700 w-6 h-6" />
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm">
                    100% Handmade
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-pink-100 rounded-full flex items-center justify-center flex-shrink-0">
                  <Heart className="text-pink-700 w-6 h-6" />
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm">
                    Made to Last
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="relative">
            <div className="absolute inset-0 bg-gradient-to-br from-purple-300 to-pink-300 rounded-full blur-3xl opacity-20"></div>
            {products.length > 0 && (
              <div className="polaroid relative z-10 rotate-2 mx-auto md:mr-0 max-w-sm">
                <div className="aspect-square bg-stone-100 overflow-hidden mb-4 border border-stone-200">
                  <img
                    src={products[0].node.featuredImage?.url}
                    alt={products[0].node.title}
                    className="w-full h-full object-cover transition-transform duration-700 hover:scale-110"
                  />
                </div>
                <div className="text-center">
                  <h3 className="font-bold text-slate-900 text-xl font-serif text-slate-900!">
                    Featured This Week
                  </h3>
                  <p className="text-slate-600 text-sm italic">
                    {products[0].node.title}
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Unified Product Grid (Removing Multiple Category Galleries) */}
        <div className="py-24">
          <div className="text-center mb-16">
            <h3 className="text-4xl font-serif text-slate-900 mb-4 font-bold">
              The Collection
            </h3>
            <p className="text-slate-500 max-w-lg mx-auto">
              Explore all our hand-woven designs. Click any product to customize
              and forge your own legacy.
            </p>
          </div>
          <ProductGrid />
        </div>

        <AboutSection />
      </main>

      <div className="h-20"></div>
    </div>
  );
}
