// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import Navbar from "../components/Navbar";
import ProductGallery from "../components/ProductGallery";
import { getAllProducts } from "../lib/shopify";
import { Sparkles, Heart, Instagram, Facebook, Mail, Hand, HeartHandshake } from "lucide-react";
import AboutSection from "../components/AboutSection";

export const dynamic = 'force-dynamic';

/** Autogenerated documentation for Home by Lukas Swarm. */
export default async function Home() {
  let products = [];
  try {
    products = await getAllProducts();
    console.log("🐝 [HIVE_BEE] Fetched Products Count:", products.length);
  } catch (e) {
    console.error("Shopify Fetch Error:", e);
  }

  return (
    <div className="min-h-screen">
      <Navbar />

      {/* SPACER */}
      <div style={{ height: "40vh" }}></div>

      <main className="max-w-7xl mx-auto px-6 pb-24 relative z-10">
        
        {/* HERO SECTION */}
        <div className="grid md:grid-cols-2 gap-12 items-center py-12 mb-20">
          
          {/* Left: Text Content */}
          <div className="text-center md:text-left space-y-6">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-purple-100 rounded-full text-purple-900 text-xs font-bold tracking-wider">
              <Sparkles className="w-3 h-3" />
              <span>HANDCRAFTED WITH LOVE</span>
            </div>
            
            <h2 className="text-5xl md:text-6xl font-serif italic leading-tight text-slate-900">
              Every Knot<br/>
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-600 via-pink-600 to-rose-600">
                Tells a Story
              </span>
            </h2>
            
            <p className="text-lg text-slate-600 leading-relaxed max-w-xl mx-auto md:mx-0">
              From my hands to yours. Each keychain is lovingly woven with premium materials. Not mass-produced. Just handmade magic.
            </p>

            <div className="flex flex-wrap gap-6 pt-4 justify-center md:justify-start">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
                   {/* Simplified Icon */}
                  <HeartHandshake className="text-purple-700 w-6 h-6" />
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm">100% Handmade</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-pink-100 rounded-full flex items-center justify-center flex-shrink-0">
                  <Heart className="text-pink-700 w-6 h-6" />
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm">Made to Last</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right: Featured Image Showcase */}
          <div className="relative">
            <div className="absolute inset-0 bg-gradient-to-br from-purple-300 to-pink-300 rounded-full blur-3xl opacity-20"></div>
            {products.length > 0 && (
              <div className="polaroid relative z-10 rotate-2">
                <div className="aspect-square bg-gray-100 overflow-hidden mb-4 border border-gray-200">
                  <img 
                    src={products[0].node.featuredImage?.url || "https://i.postimg.cc/GT8fy3KT/1473986136160.jpg"} 
                    alt={products[0].node.title} 
                    className="w-full h-full object-cover transition-transform duration-700 hover:scale-110" 
                  />
                </div>
                <div className="text-center">
                  <h3 className="font-bold text-slate-900 text-xl font-serif">Featured This Week</h3>
                  <p className="text-slate-600 text-sm italic">{products[0].node.title}</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Product Gallery (Grid + Filters) */}
        <ProductGallery products={products} />

        <AboutSection />
      </main>

      {/* FOOTER */}
      <footer className="bg-slate-900 text-slate-300 py-16 relative z-10">
        <div className="max-w-6xl mx-auto px-6 flex flex-col items-center text-center">
          <div className="mb-8">
            <img 
              src="https://i.postimg.cc/cvyv100W/Untitled_design_(2).png" 
              className="h-20 mx-auto object-contain" 
              alt="Logo"
            />
          </div>
          <h2 className="text-2xl font-serif text-white mb-8">Lisa's Custom Keychains</h2>
          <div className="flex gap-8 mb-12">
            <a href="#" className="hover:text-purple-400 hover:-translate-y-1 transition-all"><Instagram /></a>
            <a href="#" className="hover:text-purple-400 hover:-translate-y-1 transition-all"><Facebook /></a>
            <a href="#" className="hover:text-purple-400 hover:-translate-y-1 transition-all"><Mail /></a>
          </div>
          <p className="text-xs opacity-50 tracking-widest uppercase">&copy; 2025 LCK Designs.</p>
        </div>
      </footer>
    </div>
  );
}
