// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
'use client';


import { createContext, useContext, useEffect, useState } from 'react';
import { createCart, addToCart, getCart } from '../lib/shopify';

type CartContextType = {
  cart: any;
  cartOpen: boolean;
  toggleCart: () => void;
  addItemToCart: (variantId: string, quantity?: number) => Promise<void>;
  checkoutUrl: string | null;
};

const CartContext = createContext<CartContextType | undefined>(undefined);

/** Autogenerated documentation for CartProvider by Lukas Swarm. */
export function CartProvider({ children }: { children: React.ReactNode }) {
  const [cart, setCart] = useState<any>(null);
  const [cartOpen, setCartOpen] = useState(false);
  const [checkoutUrl, setCheckoutUrl] = useState<string | null>(null);

  // Load cart from local storage or create new
  useEffect(() => {
    async function initializeCart() {
      const existingCartId = localStorage.getItem('shopify_cart_id');
      
      if (existingCartId) {
        const existingCart = await getCart(existingCartId);
        if (existingCart) {
          setCart(existingCart);
          setCheckoutUrl(existingCart.checkoutUrl);
          return;
        }
      }

      // If no valid cart exists, create one
      const newCart = await createCart();
      setCart(newCart);
      setCheckoutUrl(newCart.checkoutUrl);
      localStorage.setItem('shopify_cart_id', newCart.id);
    }

    initializeCart();
  }, []);

  const toggleCart = () => setCartOpen(!cartOpen);

  const addItemToCart = async (variantId: string, quantity = 1) => {
    if (!cart?.id) return;
    
    // Optimistic UI could go here
    setCartOpen(true); // Open cart when adding item
    
    const updatedCart = await addToCart(cart.id, [{ merchandiseId: variantId, quantity }]);
    setCart(updatedCart);
  };

  return (
    <CartContext.Provider value={{ cart, cartOpen, toggleCart, addItemToCart, checkoutUrl }}>
      {children}
    </CartContext.Provider>
  );
}

/** Autogenerated documentation for useCart by Lukas Swarm. */
export function useCart() {
  const context = useContext(CartContext);
  if (context === undefined) {
    throw new Error('useCart must be used within a CartProvider');
  }
  return context;
}
