// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
'use client';


import { useCart } from './CartProvider';
import { X, ShoppingBag, Trash2 } from 'lucide-react';
import Image from 'next/image';
import { motion } from "framer-motion";

/** Autogenerated documentation for CartDrawer by Lukas Swarm. */
export default function CartDrawer() {
  const { cart, cartOpen, toggleCart, checkoutUrl } = useCart();
  const quantity = cart?.totalQuantity || 0;
  const lines = cart?.lines?.edges || [];

  return (
    <>
      {/* Backdrop */}
      <div 
        className={`fixed inset-0 bg-black/50 z-[60] transition-opacity duration-300 ${cartOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'}`} 
        onClick={toggleCart}
      />
      
      {/* Drawer */}
      <div className={`fixed top-0 right-0 h-full w-full max-w-md bg-[#fdfbf7] z-[70] shadow-2xl transform transition-transform duration-300 ease-in-out ${cartOpen ? 'translate-x-0' : 'translate-x-full'}`}>
        <div className="flex flex-col h-full bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')]">
          
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-stone-200">
            <h2 className="font-serif text-2xl text-slate-900 flex items-center gap-2">
              <ShoppingBag className="w-6 h-6 text-purple-700" />
              Your Bag <span className="text-sm font-sans text-stone-500 font-normal">({quantity})</span>
            </h2>
            <button onClick={toggleCart} className="p-2 hover:bg-stone-100 rounded-full transition-colors text-slate-600">
              <X className="w-6 h-6" />
            </button>
          </div>

          {/* Items */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {lines.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center space-y-4 opacity-50">
                <ShoppingBag className="w-16 h-16 text-stone-300" />
                <p className="font-serif text-xl text-stone-500">Your bag is empty.</p>
                <button onClick={toggleCart} className="text-purple-700 font-bold hover:underline">Start Shopping</button>
              </div>
            ) : (
              lines.map(({ node }: any) => (
                <div key={node.id} className="flex gap-4">
                  <div className="w-20 h-20 bg-stone-100 rounded-md overflow-hidden flex-shrink-0 border border-stone-200">
                    {node.merchandise.product.featuredImage && (
                       <img 
                         src={node.merchandise.product.featuredImage.url} 
                         alt={node.merchandise.product.featuredImage.altText} 
                         className="w-full h-full object-cover"
                       />
                    )}
                  </div>
                  <div className="flex-1">
                    <h3 className="font-serif font-bold text-slate-900">{node.merchandise.product.title}</h3>
                    <p className="text-stone-500 text-sm">{node.merchandise.title !== 'Default Title' ? node.merchandise.title : ''}</p>
                    <div className="flex justify-between items-center mt-2">
                        <span className="text-sm font-bold text-slate-800">Qty: {node.quantity}</span>
                        <span className="text-sm font-bold text-purple-700">
                            ${(parseFloat(node.merchandise.price.amount) * node.quantity).toFixed(2)}
                        </span>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Footer */}
          {lines.length > 0 && (
            <div className="p-6 border-t border-stone-200 bg-white/50 backdrop-blur-sm">
                <a 
                  href={checkoutUrl || '#'} 
                  className="block w-full bg-slate-900 text-white text-center py-4 rounded-full font-bold tracking-widest hover:bg-purple-700 transition-colors"
                >
                    CHECKOUT
                </a>
                <p className="text-center text-[10px] uppercase tracking-widest text-stone-400 mt-4">
                    Secure Checkout via Shopify
                </p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
