// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
'use client';


import { useState, useEffect } from 'react';
import { ShoppingBag, Menu, X } from 'lucide-react';
import { useCart } from './CartProvider';

/** Autogenerated documentation for Navbar by Lukas Swarm. */
export default function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const { toggleCart, cart } = useCart();
  const quantity = cart?.totalQuantity || 0;

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <>
      <nav
        className={`fixed top-0 w-full z-50 transition-[height,background-color] duration-600 ${
          isScrolled 
            ? 'h-20 bg-white/95 backdrop-blur-md border-b border-stone-200 shadow-sm' 
            : 'h-[40vh] bg-transparent'
        }`}
        style={{ transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)' }}
      >
        <div className="max-w-7xl mx-auto px-6 h-full">
          <div 
            className={`flex items-center h-full transition-all duration-600 ${
              isScrolled ? 'flex-row justify-between' : 'flex-col justify-center'
            }`}
          >
            {/* LEFT LINKS */}
            <div 
              className={`hidden md:flex flex-1 justify-start space-x-8 text-sm font-medium tracking-widest text-slate-600 transition-opacity duration-300 ${
                isScrolled ? 'opacity-100' : 'opacity-0 hidden'
              }`}
            >
              <a href="/" className="hover:text-purple-700 transition-colors">SHOP</a>
              <a href="/customize" className="hover:text-purple-700 transition-colors">CUSTOMIZE</a>
            </div>

            {/* LOGO */}
            <div 
              className={`flex-shrink-0 transition-transform duration-500 ${
                isScrolled ? 'scale-100' : 'scale-150'
              }`}
            >
              <img
                src="https://i.postimg.cc/cvyv100W/Untitled_design_(2).png"
                alt="Lisa's Logo"
                className="h-24 w-auto object-contain drop-shadow-[0_8px_30px_rgb(0,0,0,0.04)]"
              />
            </div>

            {/* RIGHT LINKS */}
            <div 
              className={`hidden md:flex flex-1 justify-end items-center space-x-4 transition-opacity duration-300 ${
                isScrolled ? 'opacity-100' : 'opacity-0 hidden'
              }`}
            >
              <button 
                onClick={toggleCart}
                className="text-slate-600 hover:text-purple-700 transition-colors relative"
              >
                <ShoppingBag className="w-5 h-5" />
                {quantity > 0 && (
                  <span className="absolute -top-1 -right-1 bg-purple-600 text-white text-[10px] w-4 h-4 rounded-full flex items-center justify-center">
                    {quantity}
                  </span>
                )}
              </button>
              <div className="text-sm font-medium tracking-widest text-slate-600 ml-4">
                <a href="#" className="hover:text-purple-700 transition-colors">ABOUT</a>
              </div>
            </div>

            {/* MOBILE TOGGLE */}
            <button 
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className={`md:hidden absolute right-6 text-purple-900 transition-opacity duration-300 ${
                isScrolled ? 'opacity-100' : 'opacity-0'
              }`}
            >
              {isMobileMenuOpen ? <X /> : <Menu />}
            </button>
          </div>
        </div>
      </nav>

      {/* MOBILE MENU OVERLAY */}
      <div 
        className={`fixed inset-0 bg-white z-40 flex flex-col items-center justify-center space-y-8 text-xl font-serif text-slate-900 transition-all duration-300 md:hidden ${
          isMobileMenuOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'
        }`}
        style={{ top: '80px' }}
      >
        <a href="#" className="hover:text-purple-700 transition-colors" onClick={() => setIsMobileMenuOpen(false)}>SHOP</a>
        <a href="#" className="hover:text-purple-700 transition-colors" onClick={() => setIsMobileMenuOpen(false)}>CUSTOMIZE</a>
        <a href="#" className="hover:text-purple-700 transition-colors" onClick={() => setIsMobileMenuOpen(false)}>ABOUT</a>
        <button onClick={() => { setIsMobileMenuOpen(false); toggleCart(); }} className="flex items-center gap-2 text-purple-700">
           <ShoppingBag /> Bag ({quantity})
        </button>
      </div>
    </>
  );
}
