// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
'use client';


import { useState } from 'react';
import ProductCard from './ProductCard';
import { ShopifyProduct } from '../lib/types';
import { motion } from "framer-motion";

interface ProductGalleryProps {
  products: any[]; // Using any[] for the edges array structure
}

/** Autogenerated documentation for ProductGallery by Lukas Swarm. */
export default function ProductGallery({ products }: ProductGalleryProps) {
  const [activeCategory, setActiveCategory] = useState('All');

  // Filter Logic
  const filteredProducts = products.filter(({ node }) => {
    if (activeCategory === 'All') return true;
    
    // Logic to match Shopify data to simulated categories
    const title = node.title.toLowerCase();
    const type = node.productType?.toLowerCase() || '';
    
    if (activeCategory === 'Sports') {
      return title.includes('court') || title.includes('team') || type.includes('sports');
    }
    if (activeCategory === 'Woven') {
      return title.includes('woven') || title.includes('braid') || type.includes('woven');
    }
    if (activeCategory === 'Sets') {
      return title.includes('set') || title.includes('pack') || title.includes('duo');
    }
    
    return true;
  });

  return (
    <div>
      {/* FILTERS */}
      <div className="text-center mb-12">
        <h3 className="text-3xl font-serif text-slate-900 mb-6">Gallery Collection</h3>
        <div className="inline-flex flex-wrap justify-center gap-3">
          {['All', 'Woven', 'Sports', 'Sets'].map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-6 py-2 rounded-full text-sm font-medium transition-all duration-300 shadow-lg ${
                activeCategory === category
                  ? 'bg-purple-700 text-white transform scale-105'
                  : 'bg-white text-slate-600 hover:bg-purple-50'
              }`}
            >
              {category}
            </button>
          ))}
        </div>
      </div>

      {/* GRID */}
      {filteredProducts.length === 0 ? (
         <div className="text-center py-20">
           <p className="text-stone-500 font-serif italic">No products found in this category.</p>
         </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12 px-4 transition-all duration-500 ease-in-out">
          {filteredProducts.map(({ node }: any, index: number) => {
            // Deterministic rotation based on ID or index
            const rotations = [-1, 2, -2, 1, -1.5, 1.5];
            const rotation = rotations[index % rotations.length];
            
            return (
              <ProductCard 
                key={node.id} 
                product={node} 
                rotation={rotation}
                priority={index < 3}
              />
            );
          })}
        </div>
      )}
    </div>
  );
}
