// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import { getAllProducts } from '../lib/shopify';
import ProductCard from './ProductCard';

/** Autogenerated documentation for ProductGrid by Lukas Swarm. */
export default async function ProductGrid() {
  let products = [];
  
  try {
    products = await getAllProducts();
  } catch (e) {
    console.error("Failed to fetch Shopify products:", e);
  }

  if (!products || products.length === 0) {
    return (
      <div className="text-center py-20">
        <p className="text-stone-500 font-serif italic">Loading Collection...</p>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12 px-4">
      {products.map(({ node }: any, index: number) => {
        // Deterministic rotation
        const rotations = [-1, 2, -2, 1, -1.5, 1.5];
        const rotation = rotations[index % rotations.length];
        
        return (
          <ProductCard 
            key={node.id} 
            product={node} 
            rotation={rotation}
            priority={index < 3}
          />
        );
      })}
    </div>
  );
}
