// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
import { getAllProducts, type ShopifyProdocutEdge } from "../lib/shopify";
import ProductCard from "./ProductCard";
import { Loader2 } from "lucide-react";

/** Autogenerated documentation for ProductGrid by Lukas Swarm. */
export default async function ProductGrid() {
  let products: ShopifyProdocutEdge[] = [];

  try {
    products = await getAllProducts();
  } catch (e) {
    console.error("Failed to fetch Shopify products:", e);
  }

  if (!products || products.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-40 gap-4">
        <Loader2 className="w-10 h-10 text-[#D4AF37] animate-spin opacity-50" />
        <p className="text-zinc-700 font-serif tracking-[0.2em] uppercase text-xs">
          Synchronizing Collection...
        </p>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-12 gap-y-20 px-4">
      {products.map(({ node }: ShopifyProdocutEdge, index: number) => {
        // Subtle drift rotation for the handmade feel
        const rotations = [-0.5, 0.8, -1, 0.4, -0.6, 1.2];
        const rotation = rotations[index % rotations.length];

        return (
          <ProductCard
            key={node.id}
            product={node}
            rotation={rotation}
            priority={index < 3}
          />
        );
      })}
    </div>
  );
}
