// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
"use client";

import { getAllProducts } from "../lib/shopify";
import { type ShopifyProductEdge } from "../lib/shopify/types";
import ProductCard from "./ProductCard";
import { Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";

/** Autogenerated documentation for ProductGrid by Lukas Swarm. */
export default function ProductGrid() {
  const [products, setProducts] = useState<ShopifyProductEdge[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchProducts() {
      try {
        const data = await getAllProducts();
        setProducts(data);
      } catch (e) {
        console.error("Failed to fetch Shopify products:", e);
      } finally {
        setLoading(false);
      }
    }
    fetchProducts();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-40 gap-4">
        <Loader2 className="w-10 h-10 text-[#D4AF37] animate-spin opacity-50" />
        <p className="text-zinc-700 font-serif tracking-[0.2em] uppercase text-xs">
          Synchronizing Collection...
        </p>
      </div>
    );
  }

  if (!products || products.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-40 gap-4 text-center px-4">
        <p className="text-zinc-500 font-serif italic">
          No items found in the vault. Check back soon.
        </p>
      </div>
    );
  }

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.3,
      },
    },
  };

  return (
    <motion.div
      variants={container}
      initial="hidden"
      whileInView="show"
      viewport={{ once: true, margin: "-100px" }}
      className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-12 gap-y-20 px-4"
    >
      {products.map(({ node }: ShopifyProductEdge, index: number) => {
        // Subtle drift rotation for the handmade feel
        const rotations = [-0.5, 0.8, -1, 0.4, -0.6, 1.2];
        const rotation = rotations[index % rotations.length];

        return (
          <motion.div
            key={node.id}
            variants={{
              hidden: { opacity: 0, y: 30, scale: 0.95 },
              show: { opacity: 1, y: 0, scale: 1 },
            }}
          >
            <ProductCard
              product={node}
              rotation={rotation}
              priority={index < 3}
            />
          </motion.div>
        );
      })}
    </motion.div>
  );
}
