// 🐝 [HIVE_SWARM_STAMP] Autonomously Audited by Lukas Swarm
'use client';

import { useState } from 'react';
import ProductCard from './ProductCard';
import { motion, AnimatePresence } from "framer-motion";

import { type ShopifyProductEdge } from '../lib/shopify/types';

interface ProductGalleryProps {
  products: ShopifyProductEdge[];
}

/** Autogenerated documentation for ProductGallery by Lukas Swarm. */
export default function ProductGallery({ products }: ProductGalleryProps) {
  const [activeCategory, setActiveCategory] = useState('All');
  // Dynamic filter extraction
  const categories = ['All', ...Array.from(new Set(products.map(({ node }) => node.productType).filter(Boolean)))];

  const filteredProducts = products.filter(({ node }) => {
    if (activeCategory === 'All') return true;
    const type = (node.productType || "").toLowerCase();
    const title = (node.title || "").toLowerCase();
    const active = activeCategory.toLowerCase();

    // Exact type match OR partial type match OR title contains category name
    return type === active || type.includes(active) || title.includes(active);
  });

  return (
    <div id="gallery" className="py-12">
      {/* FILTERS */}
      <div className="text-center mb-12">
        <div className="inline-flex flex-wrap justify-center gap-3">
          {categories.map((category: string) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-6 py-2 rounded-full text-sm font-medium transition-all duration-300 shadow-md ${activeCategory === category
                ? 'bg-purple-700 text-white transform scale-105'
                : 'bg-white text-slate-600 hover:bg-purple-50'
                }`}
            >
              {category}
            </button>
          ))}
        </div>
      </div>

      {/* GRID */}
      <div className="min-h-[400px]">
        <AnimatePresence mode="popLayout">
          {filteredProducts.length === 0 ? (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-20"
            >
              <p className="text-stone-500 font-serif italic">No products found in this category.</p>
            </motion.div>
          ) : (
            <motion.div
              layout
              className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-12 px-4"
            >
              {filteredProducts.map(({ node }: ShopifyProductEdge, index: number) => {
                const rotations = [-1, 2, -2, 1, -1.5, 1.5];
                const rotation = rotations[index % rotations.length];

                return (
                  <motion.div
                    key={node.id}
                    layout
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    transition={{ duration: 0.4 }}
                  >
                    <ProductCard
                      product={node}
                      rotation={rotation}
                      priority={index < 3}
                    />
                  </motion.div>
                );
              })}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
