import { motion } from 'framer-motion';
import { ShopifyProduct } from '../lib/types';
import { ShoppingBag } from 'lucide-react';
import { useCart } from './CartProvider';

interface ProductCardProps {
  product: ShopifyProduct;
  rotation: number;
  priority?: boolean;
}

/** Autogenerated documentation for ProductCard by Lukas Swarm. */
export default function ProductCard({ product, rotation, priority = false }: ProductCardProps) {
  const { title, priceRange, featuredImage } = product;
  const image = featuredImage || product.images.edges[0]?.node;
  const price = product.priceRange?.minVariantPrice?.amount || 
                product.variants?.edges[0]?.node?.price?.amount || 
                "0.00";

  const { addItemToCart } = useCart();

  const handleAddToCart = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    const variantId = product.variants?.edges[0]?.node?.id;
    if (variantId) {
      await addItemToCart(variantId);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      whileHover={{ 
        scale: 1.05, 
        rotate: 0, 
        zIndex: 10,
        boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
      }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="group relative bg-white p-4 pb-12 shadow-md cursor-pointer"
      style={{ rotate: `${rotation}deg` } as any}
    >
      {/* Polaroid Image Area */}
      <div className="relative aspect-square w-full overflow-hidden bg-stone-100 mb-4 border border-stone-200">
        {image ? (
          <img
            src={image.url}
            alt={image.altText || title}
            className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-110"
            loading={priority ? "eager" : "lazy"}
          />
        ) : (
          <div className="flex h-full items-center justify-center bg-stone-200 text-stone-400">
            No Image
          </div>
        )}
        
        {/* Mock Badge Logic based on keywords for demo purposes */}
        {title.toLowerCase().includes("team") && (
           <div className="absolute top-2 right-2 bg-pink-600 text-white px-3 py-1 text-[10px] font-bold tracking-widest uppercase shadow-[0_8px_30px_rgb(0,0,0,0.04)]">BUNDLE</div>
        )}
        {title.toLowerCase().includes("new") && (
           <div className="absolute top-2 right-2 bg-indigo-600 text-white px-3 py-1 text-[10px] font-bold tracking-widest uppercase shadow-[0_8px_30px_rgb(0,0,0,0.04)]">NEW</div>
        )}
      </div>

      {/* Caption Area */}
      <div className="text-center px-2">
        <h3 className="font-serif font-bold text-slate-900 text-lg group-hover:text-purple-700 transition-colors">
          {title}
        </h3>
        
        <div className="flex justify-between items-center border-t border-stone-100 pt-3 mt-2">
          <span className="font-bold text-slate-800">
            ${parseFloat(price).toFixed(2)}
          </span>
          <button 
            onClick={handleAddToCart}
            className="flex items-center gap-1 text-xs font-bold text-purple-900 uppercase tracking-widest group-hover:underline z-20"
          >
            <span>Shop</span>
            <ShoppingBag className="w-3 h-3" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}
