const https = require('https');
const fs = require('fs');
const path = require('path');

// --- Load Env ---
const env = {};
const envPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envPath)) {
    fs.readFileSync(envPath, 'utf8').split(/\r?\n/).forEach(line => {
        const parts = line.split('=');
        if (parts.length >= 2) {
            const key = parts[0].trim();
            const value = parts.slice(1).join('=').trim().replace(/^['"]|['"]$/g, '');
            if (key && !key.startsWith('#')) env[key] = value;
        }
    });
}

// --- Configuration ---
const domain = env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN || process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN || 'lisascustomkeychains.myshopify.com';
const storefrontAccessToken = env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN || process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN;
const adminAccessToken = env.SHOPIFY_ADMIN_API_ACCESS_TOKEN || process.env.SHOPIFY_ADMIN_API_ACCESS_TOKEN;

const MOCKS_FILE_PATH = path.join(__dirname, '../src/lib/shopify/mocks.ts');

if (!storefrontAccessToken) {
    console.error("❌ Error: NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN is missing.");
    process.exit(1);
}

// --- Query for Products (Storefront API) ---
const productsQuery = `
{
  products(first: 250) {
    edges {
      node {
        id
        title
        handle
        description
        productType
        featuredImage {
          url
          altText
        }
        priceRange {
          minVariantPrice {
            amount
            currencyCode
          }
        }
        images(first: 10) {
          edges {
            node {
              url
              altText
            }
          }
        }
        variants(first: 25) {
            edges {
                node {
                    id
                    title
                    availableForSale
                    price {
                        amount
                        currencyCode
                    }
                }
            }
        }
      }
    }
  }
}
`;

// --- Helpers ---
function fetchShopify(query) {
    return new Promise((resolve, reject) => {
        const options = {
            hostname: domain,
            path: '/api/2026-04/graphql.json',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Shopify-Storefront-Access-Token': storefrontAccessToken,
            },
        };

        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', (d) => { data += d; });
            res.on('end', () => {
                if (res.statusCode === 200) {
                    try {
                        resolve(JSON.parse(data));
                    } catch (e) {
                        reject(e);
                    }
                } else {
                    reject(new Error(`Status Code: ${res.statusCode} - ${data}`));
                }
            });
        });

        req.on('error', (e) => reject(e));
        req.write(JSON.stringify({ query }));
        req.end();
    });
}

function checkAdminDomain() {
    return new Promise((resolve) => {
        if (!adminAccessToken) {
            console.log("⚠️  Skipping Admin Domain Check (SHOPIFY_ADMIN_API_ACCESS_TOKEN missing).");
            resolve();
            return;
        }

        const options = {
            hostname: domain,
            path: '/admin/api/2026-04/shop.json',
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'X-Shopify-Access-Token': adminAccessToken,
            }
        };

        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', (chunk) => { data += chunk; });
            res.on('end', () => {
                if (res.statusCode === 200) {
                    try {
                        const json = JSON.parse(data);
                        console.log(`✅  Admin Check: Connected to ${json.shop.name} (${json.shop.myshopify_domain})`);
                        console.log(`    Primary Domain: ${json.shop.domain}`);
                    } catch (e) {
                        console.log("⚠️  Admin Check Failed to parse.");
                    }
                } else {
                    console.log(`⚠️  Admin Check Failed (Status: ${res.statusCode})`);
                }
                resolve();
            });
        });
        req.on('error', () => {
            console.log("⚠️  Admin Check Network Error.");
            resolve();
        });
        req.end();
    });
}

function generateMocksFile(products) {
    const fileContent = `// 🐝 [HIVE_SWARM_STAMP] Autonomously Extracted by Anya Sharma & Synced with Shopify
// Generated by scripts/sync_shopify_all.js at ${new Date().toISOString()}
import { ShopifyProductEdge } from "./types";

export const mockProducts: ShopifyProductEdge[] = ${JSON.stringify(products, null, 4)};
`;
    fs.writeFileSync(MOCKS_FILE_PATH, fileContent);
    console.log(`💾  Updated mocks.ts with ${products.length} products.`);
}

// --- Main Execution ---
async function main() {
    console.log(`🔄  Starting Shopify Sync...`);
    console.log(`    Target: ${domain}`);

    try {
        // 1. Check Admin Config (Async but don't block heavily)
        await checkAdminDomain();

        // 2. Fetch Products
        console.log(`📦  Fetching Products...`);
        const data = await fetchShopify(productsQuery);

        if (data.errors) {
            console.error("❌  GraphQL Errors:", data.errors);
            process.exit(1);
        }

        const products = data.data.products.edges;
        console.log(`✅  Fetched ${products.length} products.`);

        // 3. Write Mocks
        generateMocksFile(products);

        console.log(`🎉  Sync Complete!`);

    } catch (err) {
        console.error("❌  Sync Failed:", err.message);
        process.exit(1);
    }
}

main();
